export default {
  SUBMIT: 'SUBMIT',
  CANCEL: 'CANCEL',
  ACCOUNT: 'ACCOUNT',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  REGISTER: 'REGISTER',
  NEED_LOGIN: 'NEED_LOGIN',
  NEED_REGISTER: 'NEED_REGISTER',
};
